### ISSUE TITLE
How to preprocessing the dataset?

### ISSUE THREAD

**Issue by StevenSheng123** [junqiangchen/ATLAS-R2.0---Stroke-Lesion-Segmentation#1]
Hello! I want to study your project with the ATLAS_R2.0 dataset. But I get in trouble when preprocessing the dataset. I downloaded the dataset from the official website and the dictory is different with yours. Can you tell me how to preprocess the dataset? Many thanks...

**Comment by junqiangchen** [comment]
@BryceSheng it's easy,just put all data into one folder

**Comment by Uni-Summer** [comment]
hey,
Thanks for your work. BTW, how do you choose the image for validation, and whats the number of it?
Or is there any paper I can turn to help?
Thanks again!

**Comment by Uni-Summer** [comment]
> @BryceSheng it's easy,just put all data into one folder

hey,
Thanks for your work. BTW, how do you choose the image for validation, and whats the number of it?
Or is there any paper I can turn to help?
Thanks again!

**Comment by junqiangchen** [comment]
> > @BryceSheng it's easy,just put all data into one folder
> 
> hey, Thanks for your work. BTW, how do you choose the image for validation, and whats the number of it? Or is there any paper I can turn to help? Thanks again!

you can choose last 5 case for validation，you can read artical from my wechat.
